### ISSUE TITLE
When converting schema to dataclass, treat list types properly

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/scabha2#5]
Mutable types require fields with a default_factory. See e.g. here 
https://github.com/caracal-pipeline/scabha2/blob/clickify/scabha/schema_utils.py#L44

**Comment by o-smirnov** [comment]
@JSKenyon, try with the latest ``clickify`` branch. Not sure why default_factory is not working, but at least the rest works, including propagating metadata into the field metadata.

**Comment by JSKenyon** [comment]
I still seem to be getting `omegaconf.listconfig.ListConfig` objects when I would expect lists. It seems like this never gets called: https://github.com/caracal-pipeline/scabha2/blob/4220a4f5ffee8df629c3d7e71c004d587b7c5e59/scabha/cargo.py#L135-L144

**Comment by JSKenyon** [comment]
It seems that something in scabha causes the `__post_init__` methods to be run too early (before the `oc.to_object` call). As such, they retain their `oc` types rather than their normal Python types. Will continue digging.

**Comment by JSKenyon** [comment]
I believe the culprit is https://github.com/caracal-pipeline/scabha2/blob/4220a4f5ffee8df629c3d7e71c004d587b7c5e59/scabha/schema_utils.py#L91

This actually instantiates an instance of `dcls` which results in its `__post_init__` being called. I am not sure what the best way around this is.
