### ISSUE TITLE
Typo in schema_utils

### ISSUE THREAD

**Issue by JSKenyon** [caracal-pipeline/scabha2#7]
There is a small typo here: https://github.com/caracal-pipeline/scabha2/blob/ff3022874df96d934dcbb721a605248cc8f975cc/scabha/schema_utils.py#L48

There should only be a single underscore between `post` and `init`.

**Comment by o-smirnov** [comment]
Fixed in https://github.com/caracal-pipeline/scabha2/commit/4220a4f5ffee8df629c3d7e71c004d587b7c5e59
